/**
 * API Error types
 */

/**
 * Error code enumeration
 */
export enum ErrorCode {
    // Authentication (1xxx)
    UNAUTHORIZED = 'UNAUTHORIZED',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    TOKEN_EXPIRED = 'TOKEN_EXPIRED',
    SESSION_EXPIRED = 'SESSION_EXPIRED',
    EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
    ACCOUNT_SUSPENDED = 'ACCOUNT_SUSPENDED',

    // Authorization (2xxx)
    FORBIDDEN = 'FORBIDDEN',
    INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',
    ADMIN_ONLY = 'ADMIN_ONLY',
    KYC_REQUIRED = 'KYC_REQUIRED',

    // Validation (3xxx)
    VALIDATION_ERROR = 'VALIDATION_ERROR',
    INVALID_INPUT = 'INVALID_INPUT',
    MISSING_REQUIRED_FIELD = 'MISSING_REQUIRED_FIELD',
    INVALID_FORMAT = 'INVALID_FORMAT',

    // Resource (4xxx)
    NOT_FOUND = 'NOT_FOUND',
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    LOAN_NOT_FOUND = 'LOAN_NOT_FOUND',
    DOCUMENT_NOT_FOUND = 'DOCUMENT_NOT_FOUND',
    WALLET_NOT_FOUND = 'WALLET_NOT_FOUND',
    PLAN_NOT_FOUND = 'PLAN_NOT_FOUND',
    ALREADY_EXISTS = 'ALREADY_EXISTS',
    EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
    WALLET_ALREADY_CONNECTED = 'WALLET_ALREADY_CONNECTED',

    // Business Logic (5xxx)
    INELIGIBLE_FOR_LOAN = 'INELIGIBLE_FOR_LOAN',
    INSUFFICIENT_CREDIT_SCORE = 'INSUFFICIENT_CREDIT_SCORE',
    LOAN_AMOUNT_EXCEEDS_LIMIT = 'LOAN_AMOUNT_EXCEEDS_LIMIT',
    LOAN_NOT_ACTIVE = 'LOAN_NOT_ACTIVE',
    LOAN_ALREADY_REPAID = 'LOAN_ALREADY_REPAID',
    INSUFFICIENT_COLLATERAL = 'INSUFFICIENT_COLLATERAL',
    EXTENSION_NOT_ALLOWED = 'EXTENSION_NOT_ALLOWED',
    ALREADY_EXTENDED = 'ALREADY_EXTENDED',
    KYC_ALREADY_APPROVED = 'KYC_ALREADY_APPROVED',
    DOCUMENTS_INCOMPLETE = 'DOCUMENTS_INCOMPLETE',

    // Blockchain (6xxx)
    BLOCKCHAIN_ERROR = 'BLOCKCHAIN_ERROR',
    TRANSACTION_FAILED = 'TRANSACTION_FAILED',
    INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE',
    INVALID_SIGNATURE = 'INVALID_SIGNATURE',
    CONTRACT_ERROR = 'CONTRACT_ERROR',

    // External Services (7xxx)
    AI_SERVICE_ERROR = 'AI_SERVICE_ERROR',
    EMAIL_SERVICE_ERROR = 'EMAIL_SERVICE_ERROR',
    PUSH_NOTIFICATION_ERROR = 'PUSH_NOTIFICATION_ERROR',

    // Rate Limiting (8xxx)
    RATE_LIMITED = 'RATE_LIMITED',
    TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
    LOGIN_ATTEMPTS_EXCEEDED = 'LOGIN_ATTEMPTS_EXCEEDED',

    // Server (9xxx)
    INTERNAL_ERROR = 'INTERNAL_ERROR',
    SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
    DATABASE_ERROR = 'DATABASE_ERROR',
}

/**
 * API Error class interface
 */
export interface ApiError {
    code: ErrorCode;
    message: string;
    statusCode: number;
    details?: Record<string, unknown>;
}

/**
 * Validation error interface
 */
export interface ValidationError {
    field: string;
    message: string;
    value?: unknown;
}

/**
 * Error with validation details
 */
export interface ValidationErrorResponse {
    code: ErrorCode.VALIDATION_ERROR;
    message: string;
    errors: ValidationError[];
}
